export const FETCH_WORLDWIDE_JOBS_REQUEST = "FETCH_WORLDWIDE_JOBS_REQUEST";
export const FETCH_WORLDWIDE_JOBS_SUCCESSFUL = "FETCH_WORLDWIDE_JOBS_SUCCESSFUL";
export const FETCH_WORLDWIDE_JOBS_FAILED = "FETCH_WORLDWIDE_JOBS_FAILED";
export const POST_JOB = "POST_JOB";

